version: '3.8'

services:
 spotty:
  build:
   context: spottyd
   dockerfile: Dockerfile
  ports:
  - 5000:5000
  volumes:
  - ./spottyd/:/app
  command: watchmedo auto-restart -p "*.py" -R python3 -- bot.py
