version: '3.8'

services:
 spotty:
  build:
   context: spottyd
   dockerfile: Dockerfile
  ports:
  - 5000:5000
  volumes:
  - ./spottyd/:/app

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  command: --init-file /data/application/init.sql
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - ./init.sql:/data/application/init.sql
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
